### ISSUE TITLE
finish building app into package

### ISSUE THREAD

**Issue by jackhump** [jackhump/leafviz#1]
Currently, the user has to install the R package and clone the repo in order to run the app. 

Ideally, the user would just install the app and then run the app through R, rather than having to use the command line.

**Comment by MercedesBentata** [comment]
@jackhump Is this warning related to the issue you posted?

**Error in shinyAppDir(x) : App dir must contain either app.R or server.R.
Calls: <Anonymous> ... as.shiny.appobj -> as.shiny.appobj.character -> shinyAppDir
Execution halted**

If so, I did not quite understand what I have to do to solve it if I am running the code in linux/cluster?

Thanks in advance.

**Comment by jackhump** [comment]
Hi Mercedes,

yes at the moment you need to run the run_leafviz.R script within the folder that contains the ui.R and server.R files.

**Comment by jackhump** [comment]
this should be `leafviz/scripts/`

**Comment by MercedesBentata** [comment]
Thank you very much!
Not it is working fine.

**Comment by MercedesBentata** [comment]
*Now

**Comment by jackhump** [comment]
Hi Mercedes,

I just got the app working as part of the R package rather than an external script so you should be able to now just type the following in an R session:

```
library(leafviz)
leafviz("path/to/your/file.RData")
```

I'd appreciate if you could reinstall and let me know if this new functionality works for you.

Best wishes,

Jack
