### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by yyoshiaki** [jackhump/leafviz#10]
Hi,
Thank you for the nice updates! An error occurred when I installed leafviz with the following log. 

```
Error: package or namespace load failed for ‘leafviz’ in namespaceExport(ns, exports):
 undefined exports: classify_clusters
```

I think this is because the only NAMESPACE was updated without adding the function. I recommend you create Releases to enable users to specify a stable version by `remote` install or use a developmental branch.

**Comment by snashraf** [comment]
Hi, I am still getting the same error.

I have used below method for installation
remotes::install_github("jackhump/leafviz")

Regards,
Najeeb

**Comment by jackhump** [comment]
Hi @yyoshiaki and @snashraf , 

apologies for this, I got so excited added new functions that I forgot to add the classify_clusters function to the repository.

This should now be fixed.

Agreed @yyoshiaki , I need to look into releases.

**Comment by yyoshiaki** [comment]
Thank you for a cool update!
