### ISSUE TITLE
RData file prepared using prepare_results.R is corrupted and can't be read with leafviz()

### ISSUE THREAD

**Issue by gtollefson** [jackhump/leafviz#13]
I prepared an RData file from my differential splicing analysis run and have tried to load it using leafviz(). However I receive an error telling me that the RData file is corrupted. Can you help me to trouble shoot? I've pasted my commands and output below:

```
library(leafviz)
leafviz("/Users/George/TPP1_splicing_project/leafcutter/leafcutter_results/SA42.RData")
```

> leafviz("/Users/George/TPP1_splicing_project/leafcutter/leafcutter_results/SA23.RData")
>  * Welcome to Leafviz! Loading data...
> Error in load(infile, envir = .GlobalEnv) : 
>   bad restore file magic number (file may be corrupted) -- no data loaded
> In addition: Warning message:
> file ‘SA23.RData’ has magic number 'RDX3'
>   Use of save versions prior to 2 is deprecated

**Comment by jackhump** [comment]
Hi George,

Can you verify that just running load() on that file doesn't give the same error?

**Comment by gtollefson** [comment]
Hi @jackhump, 

Thank you very much for the quick response. Running load() does indeed give the same error. It seems like the RData may be malformed. I prepared it using the prepare_results.R script following the pipeline tutorial. I didn't see any error messages while running the scripts in the workflow.
