### ISSUE TITLE
Alphabetical sorting of grouping variable levels

### ISSUE THREAD

**Issue by mtassia** [jackhump/leafviz#19]
Visualization of grouping variables appears to be sorted alphabetically. For experiments leveraging multiple comparisons to the same reference group, this can cause arbitrary sign changes in dPSI which subsequently influences figure generation. Is there a way to implement reference level declaration in the core`leafviz(<infile.R>)` command?

**Comment by jackhump** [comment]
hi, the grouping variable order is set when you run leafcutter differential splicing. Leafcutter assumes that the first grouping variable of the two in your groups file is the reference, so you just need to reorder your group file accordingly.
