### ISSUE TITLE
Error in getOption("browser"): comparison (1) is possible only for atomic and list types

### ISSUE THREAD

**Issue by jeremymsimon** [jackhump/leafviz#3]
Getting this error after installing and trying to run either `leafviz()` using example or my own data

```Error in getOption("browser") == "" : 
  comparison (1) is possible only for atomic and list types
```

Any ideas what may be causing this and how I may be able to get past it?

Thanks!

**Comment by jackhump** [comment]
Hi Jeremy,

What's your operating system? And what is your default browser? I wrote this on a Mac with Chrome as the default, so there's probably something I have to add for other use cases.

**Comment by jeremymsimon** [comment]
I tried on a Mac (M1) with Chrome, running RStudio with R/4.0.3. Maybe I missed some other dependency?

**Comment by jeremymsimon** [comment]
Ah, interesting! It works in regular R, but not RStudio. Is that expected?

**Comment by jackhump** [comment]
that is intriguing, let me see if I can replicate that.

**Comment by jackhump** [comment]
ah I see, getOption("browser") returns a function in Rstudio but in regular command line R it returns a string. Give me a sec and I'll patch it.

**Comment by jackhump** [comment]
that should fix it, try again.

**Comment by jeremymsimon** [comment]
Yup, that works for me- thanks!

**Comment by jackhump** [comment]
glad to help.

Please star the repo, and don't forget to cite the original Leafcutter paper (Li et al 2018, Nat Gen)!
