### ISSUE TITLE
Incorrect default value being checked

### ISSUE THREAD

**Issue by bsouthey** [jackhump/leafviz#5]
https://github.com/jackhump/leafviz/blob/bab7994c07a113e2145de72b3f5d762a5678f76a/R/run_leafviz.R#L19
This fails if there is no browser option:
getOption("browser") == "") { : argument is of length zero"

According to the R documentation, the correct return should be NULL not an empty string!
"For getOption, the current value set for option x, or default (which defaults to NULL) if the option is unset."

Thanks,
Bruce

**Comment by jackhump** [comment]
now checks if null.
