### ISSUE TITLE
Greek symbol not correctly parsed in Windows

### ISSUE THREAD

**Issue by bsouthey** [jackhump/leafviz#6]
https://github.com/jackhump/leafviz/blob/bab7994c07a113e2145de72b3f5d762a5678f76a/R/utils.R#L17

This line cause the installation under Windows to stop (ignored if unzipped archive but not the zipped archive):
"Error : (converted from warning) unable to re-encode 'utils.R' line 17"

The greek character needs proper R handling of unicode or use a different approach. 

Thanks
Bruce

**Comment by jackhump** [comment]
my apologies, the offending character has now been removed.
