### ISSUE TITLE
Windows browser issue

### ISSUE THREAD

**Issue by bsouthey** [jackhump/leafviz#7]
Many thanks for fixing Leafviz to run under windows! 
It all works with a clean install of Windows except that the browser needs to get defined for R under Windows (really an R or Shiny bug). So I just wanted to leave it somewhere that for Windows these work arounds (actual ports may vary). The first would be preferred and is probably sufficient to have in the documentation.

1) So before starting leafviz under Windows, set the browser option (using double backward slash or a single forward slash is due to windows) such as for the main 3 browers:
 options(browser="C:\\Program Files\\Mozilla Firefox\\firefox.exe")
 options(browser="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe")
 options(browser="C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")

2) Even if leafviz is already started, you can open the URL that it is listening on  ( "Listening on http://127.0.0.1:6231") into a browser.

3) This also works under R:
> browseURL("http:///127.0.0.1:6231")
> leafviz()

**Comment by jackhump** [comment]
you're very welcome! I'll add these tips to the README.
