### ISSUE TITLE
JUM output files Visualization in Leafviz

### ISSUE THREAD

**Issue by shashibioinfo143** [jackhump/leafviz#8]
Dear sir,

I'm Shashikanth from India, I was working on mRNA Splicing event analysis. I was using JUM tool for mRNA splicing of 6 categories of splice patterns and Visualizing them in the LeafViz Shiny app which is more interactive. 

we manually edited the Cluster_Significance and effect_size txt files of leafcutter, provided their JUM output files information, and was preparing for Visualization using Script Prepare_results.R 
 
when we are executing the script Prepare_results.R all the necessary input files were given in leafcutter format but the code shows the below error.
 _"Error: Merging the per-cluster results with the per-junction effect sizes produces an empty table. Please check your input files."_

 after a quick check with the script(Prepare_results.R) and input files, we noticed that cluster IDs for leafcutter and JUM output files nomenclature were different and that might be the reason why the script couldn't take these input files. 

if you can please let us know if it's possible to use JUM output files in Leafviz for the Visualization of splicing events.

Thank you

**Comment by jackhump** [comment]
Hi Shashikanth,

That's an interesting idea. I haven't tried using JUM so I'm not familiar with the the output files. 

If you come up with a way to convert the JUM outputs into Leafviz inputs I'd be very curious.
